name: 'Weeek Task Comment Action'
description: 'Добавляет комментарий к задаче Weeek на основе ветки репозитория'
inputs:
  weeekApiKey:
    description: 'Weeek API Token'
    required: true
  branchName:
    description: 'Ветка репозитория'
    required: true
  comment:
    description: 'Комментарий для добавления в Weeek'
    required: true
  userMapping:
    description: 'Record ID GitHub аккаунтов к Weeek ID'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
