name: "Weeek Task Comment Action"
description: "Добавляет комментарий к задаче Weeek на основе ветки репозитория"
inputs:
  weeekApiKey:
    description: "Weeek API Token"
    required: true
  branchName:
    description: "Ветка репозитория"
    required: true
  comment:
    description: "Комментарий для добавления в Weeek"
    required: true
  userMapping:
    description: "Record ID GitHub аккаунтов к Weeek ID"
    required: false
  weeekLogin:
    description: "Логин Weeek аккаунта"
    required: true
  weeekPassword:
    description: "Пароль Weeek аккаунта"
    required: true
  weeekDomain:
    description: "Домен Weeek сервиса"
    required: true
  weeekProjectId:
    description: "ID проекта в Weeek"
    required: true
runs:
  using: composite
  steps:
    - uses: tj-actions/puppeteer@v5
      with:
        files: dist/index.js
