name: "Weeek Task Comment Action"
description: "Добавляет комментарий к задаче Weeek на основе ветки репозитория"
inputs:
  weeekApiKey:
    description: "Weeek API Token"
    required: true
  branchName:
    description: "Ветка репозитория"
    required: true
  comment:
    description: "Комментарий для добавления в Weeek"
    required: true
  userMapping:
    description: "Record ID GitHub аккаунтов к Weeek ID"
    required: false
  weeekLogin:
    description: "Логин Weeek аккаунта"
    required: true
  weeekPassword:
    description: "Пароль Weeek аккаунта"
    required: true
  weeekDomain:
    description: "Домен Weeek сервиса"
    required: true
  weeekProjectId:
    description: "ID проекта в Weeek"
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Initialize Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
#      env:
#        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"

#    - name: Build and run Action
#      uses: mujo-code/puppeteer-headful@18.9.0
#      env:
#        CI: "true"
#      with:
#        args: npm run build && npm run start

    - name: Build Action
      shell: 'bash'
      run: npm run build

    - name: Run Action
      shell: 'bash'
      run: npm run start